Repository JoyZhang2023/Scholars-Saga, pull requests merged in 2024-08, with the labels that each got.

#27 scholars-saga_2_5_student-profile-page-creation
  app/home/page.tsx
  app/page.tsx
  app/profile/page.tsx
  components/Navbar_ProfilePage.tsx
  components/ProfilePage.tsx
  components/styles/ProfileCard.module.css
  components/styles/ProfilePage.module.css
  package-lock.json
Labels: Sprint 2

#26 12-Student-Dashboard-Creation
  .idea/.gitignore
  .idea/Scholars-Saga.iml
  .idea/modules.xml
  .idea/vcs.xml
  app/config.tsx
  app/layout.tsx
  app/page.tsx
  app/student-calendar/page.tsx
  app/student-dashboard/page.tsx
  components/Calendar_student.tsx
  components/Navbar_student.tsx
  package-lock.json
  package.json
Labels: Sprint 1

#25 scholar's-saga-2-23-admin-dashboard
  .vscode/launch.json
  app/admin/admin-dashboard/BulletinsCard.tsx
  app/admin/admin-dashboard/ResourcesCard.tsx
  app/admin/admin-dashboard/ToDosCard.tsx
  app/admin/admin-dashboard/UpcomingEventsCard.tsx
  app/admin/admin-dashboard/page.tsx
  app/globals.css
  app/page.module.css
  components/Navbar_admin.tsx
  hoc/withAdminAuth.tsx
  hooks/useAuth.tsx
  package-lock.json
  package.json
  tsconfig.json
Labels: Sprint 2

#31 scholar's-saga_2_30_database_setup
  .env.example
  .vscode/settings.json
  app/_app.tsx
  app/api/profile/route.ts
  app/api/students/[id]/route.ts
  app/api/students/route.ts
  lib/prisma.ts
  package-lock.json
  package.json
  prisma/migrations/20240818040241_add_profile_picture_field/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  public/images/eliza_profile.jpg
  tsconfig.json
Labels: Sprint 2

#33 Scholars-Saga-4-8-Booking-Appointment
  .env.example
  .env.sample
  app/api/student/booking/route.ts
  app/student/booking/layout.tsx
  app/student/booking/page.tsx
  components/LocalizationProvider.tsx
  package-lock.json
  package.json
  prisma/schema.prisma
Labels: sprint 4
